/**
 * OASIS-E Assessment Definition
 * Comprehensive OASIS-E (Outcome and Assessment Information Set) assessment
 * For Medicare-certified home health agencies
 */

import type { AssessmentDefinition } from './types';

export const oasisEAssessment: AssessmentDefinition = {
  id: 'oasis-e-001',
  type: 'oasis-e-assessment',
  title: 'OASIS-E Assessment',
  discipline: 'Skilled Nursing',
  description: 'Comprehensive OASIS-E assessment for home health certification',
  sections: [
    {
      id: 'patient-tracking',
      title: 'Patient Tracking',
      description: 'M items for patient identification and tracking',
      order: 1,
      questions: [
        {
          id: 'm0010-id',
          type: 'text',
          label: 'M0010: CMS Certification Number',
          required: true,
          helpText: 'Enter the Medicare CMS certification number',
        },
        {
          id: 'm0014-branch',
          type: 'text',
          label: 'M0014: Branch State',
          required: true,
        },
        {
          id: 'm0016-branch-id',
          type: 'text',
          label: 'M0016: Branch ID Number',
          required: true,
        },
        {
          id: 'm0018-npi',
          type: 'text',
          label: 'M0018: National Provider Identifier (NPI)',
          required: true,
        },
        {
          id: 'm0020-patient-id',
          type: 'text',
          label: 'M0020: Patient ID Number',
          required: true,
        },
        {
          id: 'm0030-soc-date',
          type: 'date',
          label: 'M0030: Start of Care Date',
          required: true,
        },
        {
          id: 'm0032-roc-date',
          type: 'date',
          label: 'M0032: Resumption of Care Date',
        },
        {
          id: 'm0040-patient-name',
          type: 'text',
          label: 'M0040: Patient Name',
          required: true,
        },
      ],
    },
    {
      id: 'clinical-record',
      title: 'Clinical Record Items',
      description: 'Demographics and medical history',
      order: 2,
      questions: [
        {
          id: 'm0050-ssn',
          type: 'text',
          label: 'M0050: Patient State of Residence',
          required: true,
        },
        {
          id: 'm0060-zip',
          type: 'text',
          label: 'M0060: Patient ZIP Code',
          required: true,
        },
        {
          id: 'm0063-medicare',
          type: 'text',
          label: 'M0063: Medicare Number',
          placeholder: 'Including suffix',
        },
        {
          id: 'm0064-ssn',
          type: 'text',
          label: 'M0064: Social Security Number',
        },
        {
          id: 'm0065-medicaid',
          type: 'text',
          label: 'M0065: Medicaid Number',
        },
        {
          id: 'm0066-dob',
          type: 'date',
          label: 'M0066: Birth Date',
          required: true,
        },
        {
          id: 'm0069-gender',
          type: 'radio',
          label: 'M0069: Gender',
          required: true,
          options: [
            { value: '1', label: '1 - Male' },
            { value: '2', label: '2 - Female' },
          ],
        },
        {
          id: 'm0140-race',
          type: 'multi-select',
          label: 'M0140: Race/Ethnicity',
          required: true,
          options: [
            { value: '1', label: 'American Indian or Alaska Native' },
            { value: '2', label: 'Asian' },
            { value: '3', label: 'Black or African American' },
            { value: '4', label: 'Hispanic or Latino' },
            { value: '5', label: 'Native Hawaiian or Pacific Islander' },
            { value: '6', label: 'White' },
          ],
        },
      ],
    },
    {
      id: 'payment-sources',
      title: 'Payment Sources',
      description: 'M items for payment and payer information',
      order: 3,
      questions: [
        {
          id: 'm0150-payer-primary',
          type: 'dropdown',
          label: 'M0150: Primary Payment Source',
          required: true,
          options: [
            { value: '0', label: '0 - None; no charge for current services' },
            { value: '1', label: '1 - Medicare (traditional fee-for-service)' },
            { value: '2', label: '2 - Medicare (HMO/managed care/Advantage plan)' },
            { value: '3', label: '3 - Medicaid (traditional fee-for-service)' },
            { value: '4', label: '4 - Medicaid (HMO/managed care)' },
            { value: '5', label: '5 - Workers\' compensation' },
            { value: '6', label: '6 - Title programs' },
            { value: '7', label: '7 - Other government' },
            { value: '8', label: '8 - Private insurance' },
            { value: '9', label: '9 - Private HMO/managed care' },
            { value: '10', label: '10 - Self-pay' },
            { value: '11', label: '11 - Other' },
            { value: 'UK', label: 'UK - Unknown' },
          ],
        },
        {
          id: 'm0150-payer-secondary',
          type: 'dropdown',
          label: 'M0150: Secondary Payment Source',
          options: [
            { value: '0', label: '0 - None' },
            { value: '1', label: '1 - Medicare (traditional fee-for-service)' },
            { value: '2', label: '2 - Medicare (HMO/managed care/Advantage plan)' },
            { value: '3', label: '3 - Medicaid (traditional fee-for-service)' },
            { value: '4', label: '4 - Medicaid (HMO/managed care)' },
            { value: '5', label: '5 - Workers\' compensation' },
            { value: '6', label: '6 - Title programs' },
            { value: '7', label: '7 - Other government' },
            { value: '8', label: '8 - Private insurance' },
            { value: '9', label: '9 - Private HMO/managed care' },
            { value: '10', label: '10 - Self-pay' },
            { value: '11', label: '11 - Other' },
            { value: 'UK', label: 'UK - Unknown' },
          ],
        },
      ],
    },
    {
      id: 'history-diagnoses',
      title: 'History and Diagnoses',
      description: 'Medical conditions and diagnoses',
      order: 4,
      questions: [
        {
          id: 'm1021-primary-diagnosis',
          type: 'text',
          label: 'M1021: Primary Diagnosis ICD-10 Code',
          required: true,
          placeholder: 'Enter ICD-10 code',
        },
        {
          id: 'm1021-primary-severity',
          type: 'radio',
          label: 'M1021: Primary Diagnosis Symptom Control Rating',
          required: true,
          options: [
            { value: '0', label: '0 - Asymptomatic, no treatment needed' },
            { value: '1', label: '1 - Symptoms well controlled with current therapy' },
            { value: '2', label: '2 - Symptoms controlled with difficulty' },
            { value: '3', label: '3 - Symptoms poorly controlled' },
          ],
        },
        {
          id: 'm1023-other-diagnosis-1',
          type: 'text',
          label: 'M1023: Other Diagnosis #1 ICD-10 Code',
          placeholder: 'Enter ICD-10 code',
        },
        {
          id: 'm1023-other-diagnosis-2',
          type: 'text',
          label: 'M1023: Other Diagnosis #2 ICD-10 Code',
          placeholder: 'Enter ICD-10 code',
        },
        {
          id: 'm1028-active-diagnoses',
          type: 'multi-select',
          label: 'M1028: Active Diagnoses - Comorbidities and Co-existing Conditions',
          options: [
            { value: '1', label: 'Peripheral Vascular Disease (PVD) or Peripheral Arterial Disease (PAD)' },
            { value: '2', label: 'Diabetes Mellitus (DM)' },
            { value: '3', label: 'None of the above' },
          ],
        },
      ],
    },
    {
      id: 'living-arrangements',
      title: 'Living Arrangements',
      description: 'Patient living situation and support',
      order: 5,
      questions: [
        {
          id: 'm1100-living-situation',
          type: 'radio',
          label: 'M1100: Patient Living Situation',
          required: true,
          options: [
            { value: '01', label: '01 - Patient lives alone' },
            { value: '02', label: '02 - Patient lives with other person(s) in the home' },
            { value: '03', label: '03 - Patient lives in congregate situation' },
          ],
        },
        {
          id: 'm1400-caregiver-assistance',
          type: 'radio',
          label: 'M1400: When is Caregiver Assistance Available?',
          required: true,
          options: [
            { value: '0', label: '0 - No caregiver available' },
            { value: '1', label: '1 - Caregiver available some of the time' },
            { value: '2', label: '2 - Caregiver available most or all of the time' },
            { value: '3', label: '3 - Caregiver availability unknown' },
            { value: 'UK', label: 'UK - Unknown' },
          ],
        },
      ],
    },
    {
      id: 'sensory-status',
      title: 'Sensory Status',
      description: 'Vision, hearing, and speech',
      order: 6,
      questions: [
        {
          id: 'm1200-vision',
          type: 'radio',
          label: 'M1200: Vision (with corrective lenses if applicable)',
          required: true,
          options: [
            { value: '0', label: '0 - Normal vision' },
            { value: '1', label: '1 - Partially impaired' },
            { value: '2', label: '2 - Severely impaired' },
          ],
        },
        {
          id: 'm1210-hearing',
          type: 'radio',
          label: 'M1210: Ability to Hear (with hearing aids if applicable)',
          required: true,
          options: [
            { value: '0', label: '0 - Adequate' },
            { value: '1', label: '1 - Mildly to moderately impaired' },
            { value: '2', label: '2 - Severely impaired' },
          ],
        },
        {
          id: 'm1220-speech',
          type: 'radio',
          label: 'M1220: Understanding of Verbal Content',
          required: true,
          options: [
            { value: '0', label: '0 - Understands' },
            { value: '1', label: '1 - Usually understands' },
            { value: '2', label: '2 - Sometimes understands' },
            { value: '3', label: '3 - Rarely or never understands' },
          ],
        },
      ],
    },
    {
      id: 'integumentary-status',
      title: 'Integumentary Status',
      description: 'Skin integrity and wounds',
      order: 7,
      questions: [
        {
          id: 'm1302-risk-factors',
          type: 'multi-select',
          label: 'M1302: Does this patient have a Risk Factor for developing pressure ulcers/injuries?',
          options: [
            { value: '1', label: 'Bed-bound for extended periods' },
            { value: '2', label: 'Moist/macerated skin' },
            { value: '3', label: 'Impaired nutritional status' },
            { value: '4', label: 'Impaired sensation or inability to feel pressure' },
            { value: '5', label: 'None of the above' },
          ],
        },
        {
          id: 'm1306-unhealed-pressure-ulcer',
          type: 'radio',
          label: 'M1306: Does this patient have at least one Unhealed Pressure Ulcer/Injury?',
          required: true,
          options: [
            { value: '0', label: '0 - No [Go to M1311]' },
            { value: '1', label: '1 - Yes' },
          ],
        },
        {
          id: 'm1307-oldest-stage-2',
          type: 'numeric',
          label: 'M1307: Oldest Stage 2 Pressure Ulcer that is present at discharge',
          min: 0,
          max: 999,
          helpText: 'Enter number of pressure ulcers',
        },
        {
          id: 'm1311-pressure-ulcer-length',
          type: 'numeric',
          label: 'M1311: Current Number of Unhealed Pressure Ulcers/Injuries at Each Stage',
          min: 0,
          max: 99,
        },
      ],
    },
    {
      id: 'functional-status',
      title: 'Functional Status - ADLs',
      description: 'Activities of Daily Living assessment',
      order: 8,
      questions: [
        {
          id: 'm1800-grooming',
          type: 'radio',
          label: 'M1800: Current Ability to Dress Upper Body safely',
          required: true,
          options: [
            { value: '0', label: '0 - Able to get in and out of bed independently' },
            { value: '1', label: '1 - Requires minimal human assistance' },
            { value: '2', label: '2 - Requires moderate or greater human assistance' },
            { value: '3', label: '3 - Dependent; does not participate' },
          ],
        },
        {
          id: 'm1810-transfer',
          type: 'radio',
          label: 'M1810: Ability to Transfer',
          required: true,
          options: [
            { value: '0', label: '0 - Able to independently transfer' },
            { value: '1', label: '1 - Able to transfer with minimal human assistance' },
            { value: '2', label: '2 - Able to bear weight and pivot during transfer' },
            { value: '3', label: '3 - Unable to transfer or bear weight' },
            { value: '4', label: '4 - Bedfast, unable to transfer' },
          ],
        },
        {
          id: 'm1820-ambulation',
          type: 'radio',
          label: 'M1820: Ability to Ambulate',
          required: true,
          options: [
            { value: '0', label: '0 - Able to independently walk' },
            { value: '1', label: '1 - With use of device, able to walk' },
            { value: '2', label: '2 - Able to walk with human assistance' },
            { value: '3', label: '3 - Chairfast, unable to ambulate' },
            { value: '4', label: '4 - Bedfast, unable to ambulate' },
          ],
        },
        {
          id: 'm1830-bathing',
          type: 'radio',
          label: 'M1830: Bathing',
          required: true,
          options: [
            { value: '0', label: '0 - Able to bathe self' },
            { value: '1', label: '1 - With use of devices, able to bathe' },
            { value: '2', label: '2 - Able to bathe with assistance from another person' },
            { value: '3', label: '3 - Unable to participate in bathing' },
          ],
        },
        {
          id: 'm1840-toileting',
          type: 'radio',
          label: 'M1840: Toilet Transferring',
          required: true,
          options: [
            { value: '0', label: '0 - Able to get to and from toilet independently' },
            { value: '1', label: '1 - When reminded, able to get to and from toilet' },
            { value: '2', label: '2 - Unable to get to and from toilet but is able to use bedside commode' },
            { value: '3', label: '3 - Unable to get to and from toilet or bedside commode' },
          ],
        },
      ],
    },
    {
      id: 'medications',
      title: 'Medications',
      description: 'Medication management and reconciliation',
      order: 9,
      questions: [
        {
          id: 'm2001-drug-regimen-review',
          type: 'radio',
          label: 'M2001: Drug Regimen Review',
          required: true,
          options: [
            { value: '0', label: '0 - No - No issues found' },
            { value: '1', label: '1 - Yes - Issues found during review' },
            { value: '9', label: '9 - NA - Patient not taking any medications' },
          ],
        },
        {
          id: 'm2003-medication-intervention',
          type: 'multi-select',
          label: 'M2003: Medication Follow-up',
          options: [
            { value: '1', label: 'Physician contacted' },
            { value: '2', label: 'Medication error identified' },
            { value: '3', label: 'Medication list updated' },
            { value: '4', label: 'Patient/caregiver education provided' },
            { value: '5', label: 'None of the above' },
          ],
        },
        {
          id: 'm2010-high-risk-drugs',
          type: 'multi-select',
          label: 'M2010: High-Risk Drug Classes',
          options: [
            { value: '1', label: 'Anticoagulant' },
            { value: '2', label: 'Antiplatelet' },
            { value: '3', label: 'Hypoglycemic' },
            { value: '4', label: 'Opioid' },
            { value: '5', label: 'None of the above' },
          ],
        },
        {
          id: 'm2020-management',
          type: 'radio',
          label: 'M2020: Management of Oral Medications',
          required: true,
          options: [
            { value: '0', label: '0 - Able to independently take correct medication(s)' },
            { value: '1', label: '1 - Able to take medication if prepared in advance' },
            { value: '2', label: '2 - Unable to take medication unless administered' },
            { value: 'NA', label: 'NA - No oral medications prescribed' },
          ],
        },
      ],
    },
    {
      id: 'care-management',
      title: 'Care Management',
      description: 'Emergent care and hospitalizations',
      order: 10,
      questions: [
        {
          id: 'm2102-care-type',
          type: 'multi-select',
          label: 'M2102: Types and Sources of Assistance',
          options: [
            { value: '1', label: 'ADL assistance' },
            { value: '2', label: 'IADL assistance' },
            { value: '3', label: 'Medication administration' },
            { value: '4', label: 'Medical procedures/treatments' },
            { value: '5', label: 'Management oversight/safety' },
            { value: '6', label: 'None of the above' },
          ],
        },
        {
          id: 'm2200-therapy-need',
          type: 'radio',
          label: 'M2200: Therapy Need',
          required: true,
          options: [
            { value: '0', label: '0 - No therapy services needed' },
            { value: '1', label: '1 - Physical therapy needed' },
            { value: '2', label: '2 - Occupational therapy needed' },
            { value: '3', label: '3 - Speech therapy needed' },
            { value: '4', label: '4 - Multiple therapy services needed' },
          ],
        },
      ],
    },
    {
      id: 'emergent-care',
      title: 'Emergent Care',
      description: 'Emergency department visits and hospitalizations',
      order: 11,
      questions: [
        {
          id: 'm2410-emergent-care',
          type: 'radio',
          label: 'M2410: Emergent Care',
          required: true,
          options: [
            { value: '0', label: '0 - No emergent care since last assessment' },
            { value: '1', label: '1 - Yes, used hospital emergency department WITHOUT hospitalization' },
            { value: '2', label: '2 - Yes, admitted to hospital' },
            { value: '3', label: '3 - Yes, both emergency department AND hospital admission' },
            { value: 'UK', label: 'UK - Unknown' },
          ],
        },
        {
          id: 'm2420-discharge-disposition',
          type: 'radio',
          label: 'M2420: Discharge Disposition',
          options: [
            { value: '1', label: '1 - Patient remained in community (not admitted)' },
            { value: '2', label: '2 - Patient admitted to nursing home' },
            { value: '3', label: '3 - Patient admitted to hospital' },
            { value: '4', label: '4 - Patient discharged to hospice' },
            { value: '5', label: '5 - Other' },
            { value: 'UK', label: 'UK - Unknown' },
          ],
        },
      ],
    },
  ],
};
