/**
 * OCCUPATIONAL THERAPY ASSESSMENT CONFIGURATION
 * 
 * Configuration-driven definition for Occupational Therapy Evaluation/Visit Note
 * Used for OT evaluations, ADL assessments, and treatment visits
 * 
 * @version 1.0.0
 * @compliance AOTA Guidelines, Medicare, State Regulations
 */

import type { AssessmentTypeConfiguration } from '../types/assessmentTypes';

export const OCCUPATIONAL_THERAPY_CONFIGURATION: AssessmentTypeConfiguration = {
  id: 'occupational-therapy-eval-2024',
  name: 'Occupational Therapy Evaluation',
  version: 'OT Assessment v2024.1',
  category: 'clinical-visit',
  
  sections: [
    {
      id: 'visit-info',
      title: 'Visit Information',
      description: 'Basic visit details and context',
      order: 1,
      questions: [
        {
          id: 'visit-type',
          text: 'Visit Type',
          type: 'single-select',
          required: true,
          order: 1,
          options: [
            { value: 'initial-eval', label: 'Initial Evaluation', order: 1 },
            { value: 're-eval', label: 'Re-evaluation', order: 2 },
            { value: 'treatment', label: 'Treatment Visit', order: 3 },
            { value: 'discharge', label: 'Discharge Evaluation', order: 4 },
          ],
        },
        {
          id: 'visit-date',
          text: 'Visit Date',
          type: 'date',
          required: true,
          order: 2,
        },
        {
          id: 'visit-duration',
          text: 'Visit Duration (minutes)',
          type: 'number',
          required: true,
          order: 3,
          validation: { min: 15, max: 180 },
        },
        {
          id: 'referral-reason',
          text: 'Reason for Referral',
          type: 'long-text',
          required: true,
          order: 4,
        },
        {
          id: 'primary-diagnosis',
          text: 'Primary Diagnosis',
          type: 'text',
          required: true,
          order: 5,
        },
        {
          id: 'living-situation',
          text: 'Living Situation',
          type: 'single-select',
          required: true,
          order: 6,
          options: [
            { value: 'alone', label: 'Lives Alone', order: 1 },
            { value: 'spouse', label: 'Lives with Spouse/Partner', order: 2 },
            { value: 'family', label: 'Lives with Family', order: 3 },
            { value: 'caregiver', label: 'Lives with Caregiver', order: 4 },
            { value: 'alf', label: 'Assisted Living Facility', order: 5 },
          ],
        },
      ],
    },

    {
      id: 'adl-assessment',
      title: 'Activities of Daily Living (ADLs)',
      description: 'Basic self-care activities assessment',
      order: 2,
      questions: [
        {
          id: 'bathing',
          text: 'Bathing/Showering',
          type: 'single-select',
          required: true,
          order: 1,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'max-assist', label: 'Maximum Assistance', order: 6 },
            { value: 'dependent', label: 'Totally Dependent', order: 7 },
          ],
        },
        {
          id: 'dressing-upper',
          text: 'Dressing - Upper Body',
          type: 'single-select',
          required: true,
          order: 2,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'max-assist', label: 'Maximum Assistance', order: 6 },
            { value: 'dependent', label: 'Totally Dependent', order: 7 },
          ],
        },
        {
          id: 'dressing-lower',
          text: 'Dressing - Lower Body',
          type: 'single-select',
          required: true,
          order: 3,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'max-assist', label: 'Maximum Assistance', order: 6 },
            { value: 'dependent', label: 'Totally Dependent', order: 7 },
          ],
        },
        {
          id: 'grooming',
          text: 'Grooming (hair, teeth, face)',
          type: 'single-select',
          required: true,
          order: 4,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'max-assist', label: 'Maximum Assistance', order: 6 },
            { value: 'dependent', label: 'Totally Dependent', order: 7 },
          ],
        },
        {
          id: 'toileting',
          text: 'Toileting',
          type: 'single-select',
          required: true,
          order: 5,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'max-assist', label: 'Maximum Assistance', order: 6 },
            { value: 'dependent', label: 'Totally Dependent', order: 7 },
          ],
        },
        {
          id: 'feeding',
          text: 'Feeding/Eating',
          type: 'single-select',
          required: true,
          order: 6,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'max-assist', label: 'Maximum Assistance', order: 6 },
            { value: 'dependent', label: 'Totally Dependent', order: 7 },
          ],
        },
        {
          id: 'adaptive-equipment-adl',
          text: 'Adaptive Equipment Used for ADLs',
          type: 'multi-select',
          required: false,
          order: 7,
          options: [
            { value: 'reacher', label: 'Reacher/Grabber', order: 1 },
            { value: 'sock-aid', label: 'Sock Aid', order: 2 },
            { value: 'dressing-stick', label: 'Dressing Stick', order: 3 },
            { value: 'button-hook', label: 'Button Hook', order: 4 },
            { value: 'long-handled-sponge', label: 'Long-Handled Sponge', order: 5 },
            { value: 'shower-chair', label: 'Shower Chair/Bench', order: 6 },
            { value: 'raised-toilet-seat', label: 'Raised Toilet Seat', order: 7 },
            { value: 'utensils', label: 'Adaptive Utensils', order: 8 },
          ],
        },
      ],
    },

    {
      id: 'iadl-assessment',
      title: 'Instrumental ADLs (IADLs)',
      description: 'Complex daily living activities assessment',
      order: 3,
      questions: [
        {
          id: 'meal-prep',
          text: 'Meal Preparation',
          type: 'single-select',
          required: true,
          order: 1,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'dependent', label: 'Totally Dependent', order: 6 },
            { value: 'not-applicable', label: 'Not Applicable', order: 7 },
          ],
        },
        {
          id: 'housekeeping',
          text: 'Light Housekeeping',
          type: 'single-select',
          required: true,
          order: 2,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'dependent', label: 'Totally Dependent', order: 6 },
            { value: 'not-applicable', label: 'Not Applicable', order: 7 },
          ],
        },
        {
          id: 'laundry',
          text: 'Laundry',
          type: 'single-select',
          required: true,
          order: 3,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'min-assist', label: 'Minimal Assistance', order: 4 },
            { value: 'mod-assist', label: 'Moderate Assistance', order: 5 },
            { value: 'dependent', label: 'Totally Dependent', order: 6 },
            { value: 'not-applicable', label: 'Not Applicable', order: 7 },
          ],
        },
        {
          id: 'medication-management',
          text: 'Medication Management',
          type: 'single-select',
          required: true,
          order: 4,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'supervision', label: 'Supervision', order: 3 },
            { value: 'assist-required', label: 'Assistance Required', order: 4 },
            { value: 'dependent', label: 'Totally Dependent', order: 5 },
          ],
        },
        {
          id: 'shopping',
          text: 'Shopping/Errands',
          type: 'single-select',
          required: true,
          order: 5,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'supervision', label: 'Supervision', order: 2 },
            { value: 'assist-required', label: 'Assistance Required', order: 3 },
            { value: 'dependent', label: 'Totally Dependent', order: 4 },
            { value: 'not-applicable', label: 'Not Applicable', order: 5 },
          ],
        },
        {
          id: 'phone-use',
          text: 'Telephone Use',
          type: 'single-select',
          required: true,
          order: 6,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'setup-assist', label: 'Setup Assistance Only', order: 2 },
            { value: 'assist-required', label: 'Assistance Required', order: 3 },
            { value: 'unable', label: 'Unable', order: 4 },
          ],
        },
        {
          id: 'financial-management',
          text: 'Financial Management',
          type: 'single-select',
          required: false,
          order: 7,
          options: [
            { value: 'independent', label: 'Independent', order: 1 },
            { value: 'supervision', label: 'Supervision', order: 2 },
            { value: 'assist-required', label: 'Assistance Required', order: 3 },
            { value: 'dependent', label: 'Totally Dependent', order: 4 },
          ],
        },
      ],
    },

    {
      id: 'fine-motor-cognitive',
      title: 'Fine Motor & Cognitive Skills',
      description: 'Upper extremity function and cognitive status',
      order: 4,
      questions: [
        {
          id: 'hand-dominance',
          text: 'Hand Dominance',
          type: 'single-select',
          required: true,
          order: 1,
          options: [
            { value: 'right', label: 'Right', order: 1 },
            { value: 'left', label: 'Left', order: 2 },
            { value: 'ambidextrous', label: 'Ambidextrous', order: 3 },
          ],
        },
        {
          id: 'grip-strength-right',
          text: 'Grip Strength - Right Hand (lbs)',
          type: 'number',
          required: false,
          order: 2,
        },
        {
          id: 'grip-strength-left',
          text: 'Grip Strength - Left Hand (lbs)',
          type: 'number',
          required: false,
          order: 3,
        },
        {
          id: 'fine-motor-skills',
          text: 'Fine Motor Skills Assessment',
          type: 'single-select',
          required: true,
          order: 4,
          options: [
            { value: 'wnl', label: 'Within Normal Limits', order: 1 },
            { value: 'mild-impair', label: 'Mild Impairment', order: 2 },
            { value: 'mod-impair', label: 'Moderate Impairment', order: 3 },
            { value: 'severe-impair', label: 'Severe Impairment', order: 4 },
          ],
        },
        {
          id: 'coordination',
          text: 'Upper Extremity Coordination',
          type: 'single-select',
          required: true,
          order: 5,
          options: [
            { value: 'wnl', label: 'Within Normal Limits', order: 1 },
            { value: 'mild-impair', label: 'Mild Impairment', order: 2 },
            { value: 'mod-impair', label: 'Moderate Impairment', order: 3 },
            { value: 'severe-impair', label: 'Severe Impairment', order: 4 },
          ],
        },
        {
          id: 'cognitive-status',
          text: 'Cognitive Status',
          type: 'single-select',
          required: true,
          order: 6,
          options: [
            { value: 'alert-oriented', label: 'Alert & Oriented x4', order: 1 },
            { value: 'mild-confusion', label: 'Mild Confusion', order: 2 },
            { value: 'mod-confusion', label: 'Moderate Confusion', order: 3 },
            { value: 'severe-impair', label: 'Severe Cognitive Impairment', order: 4 },
          ],
        },
        {
          id: 'memory-assessment',
          text: 'Memory Assessment',
          type: 'single-select',
          required: false,
          order: 7,
          options: [
            { value: 'intact', label: 'Intact', order: 1 },
            { value: 'mild-impair', label: 'Mild Impairment', order: 2 },
            { value: 'mod-impair', label: 'Moderate Impairment', order: 3 },
            { value: 'severe-impair', label: 'Severe Impairment', order: 4 },
          ],
        },
        {
          id: 'safety-awareness',
          text: 'Safety Awareness/Judgment',
          type: 'single-select',
          required: true,
          order: 8,
          options: [
            { value: 'appropriate', label: 'Appropriate', order: 1 },
            { value: 'impulsive', label: 'Impulsive at Times', order: 2 },
            { value: 'impaired', label: 'Impaired Judgment', order: 3 },
            { value: 'unsafe', label: 'Unsafe - Requires Supervision', order: 4 },
          ],
        },
      ],
    },

    {
      id: 'home-environment',
      title: 'Home Environment & Safety',
      description: 'Home assessment and modification needs',
      order: 5,
      questions: [
        {
          id: 'home-type',
          text: 'Home Type',
          type: 'single-select',
          required: true,
          order: 1,
          options: [
            { value: 'single-story', label: 'Single Story Home', order: 1 },
            { value: 'multi-story', label: 'Multi-Story Home', order: 2 },
            { value: 'apartment', label: 'Apartment', order: 3 },
            { value: 'mobile-home', label: 'Mobile Home', order: 4 },
            { value: 'alf', label: 'Assisted Living', order: 5 },
          ],
        },
        {
          id: 'bedroom-location',
          text: 'Bedroom Location',
          type: 'single-select',
          required: false,
          order: 2,
          options: [
            { value: 'main-floor', label: 'Main Floor', order: 1 },
            { value: 'upstairs', label: 'Upstairs', order: 2 },
            { value: 'basement', label: 'Basement', order: 3 },
          ],
        },
        {
          id: 'bathroom-access',
          text: 'Bathroom Accessibility',
          type: 'single-select',
          required: true,
          order: 3,
          options: [
            { value: 'accessible', label: 'Fully Accessible', order: 1 },
            { value: 'limited', label: 'Limited Access', order: 2 },
            { value: 'difficult', label: 'Difficult Access', order: 3 },
            { value: 'inaccessible', label: 'Not Accessible', order: 4 },
          ],
        },
        {
          id: 'home-safety-concerns',
          text: 'Home Safety Concerns',
          type: 'multi-select',
          required: false,
          order: 4,
          options: [
            { value: 'trip-hazards', label: 'Trip Hazards (rugs, cords)', order: 1 },
            { value: 'poor-lighting', label: 'Poor Lighting', order: 2 },
            { value: 'stairs', label: 'Stairs Without Handrails', order: 3 },
            { value: 'narrow-doorways', label: 'Narrow Doorways', order: 4 },
            { value: 'bathroom-unsafe', label: 'Bathroom Safety Issues', order: 5 },
            { value: 'clutter', label: 'Excessive Clutter', order: 6 },
          ],
        },
        {
          id: 'home-modifications-needed',
          text: 'Home Modifications Recommended',
          type: 'multi-select',
          required: false,
          order: 5,
          options: [
            { value: 'grab-bars', label: 'Grab Bars (bathroom)', order: 1 },
            { value: 'ramp', label: 'Ramp', order: 2 },
            { value: 'stair-rails', label: 'Stair Rails', order: 3 },
            { value: 'raised-toilet', label: 'Raised Toilet Seat', order: 4 },
            { value: 'shower-chair', label: 'Shower Chair/Bench', order: 5 },
            { value: 'bedside-commode', label: 'Bedside Commode', order: 6 },
            { value: 'improved-lighting', label: 'Improved Lighting', order: 7 },
          ],
        },
        {
          id: 'dme-needed',
          text: 'DME/Equipment Needed',
          type: 'multi-select',
          required: false,
          order: 6,
          options: [
            { value: 'reacher', label: 'Reacher/Grabber', order: 1 },
            { value: 'sock-aid', label: 'Sock Aid', order: 2 },
            { value: 'walker', label: 'Walker', order: 3 },
            { value: 'wheelchair', label: 'Wheelchair', order: 4 },
            { value: 'hospital-bed', label: 'Hospital Bed', order: 5 },
            { value: 'bedside-table', label: 'Over-Bed Table', order: 6 },
          ],
        },
      ],
    },

    {
      id: 'interventions',
      title: 'Treatment Interventions',
      description: 'Therapeutic interventions provided during visit',
      order: 6,
      questions: [
        {
          id: 'interventions-provided',
          text: 'Interventions Provided',
          type: 'multi-select',
          required: true,
          order: 1,
          options: [
            { value: 'adl-training', label: 'ADL Training', order: 1 },
            { value: 'iadl-training', label: 'IADL Training', order: 2 },
            { value: 'therapeutic-exercise', label: 'Therapeutic Exercise (UE)', order: 3 },
            { value: 'fine-motor-training', label: 'Fine Motor Training', order: 4 },
            { value: 'cognitive-training', label: 'Cognitive Training', order: 5 },
            { value: 'adaptive-equipment', label: 'Adaptive Equipment Training', order: 6 },
            { value: 'home-safety', label: 'Home Safety Education', order: 7 },
            { value: 'energy-conservation', label: 'Energy Conservation Techniques', order: 8 },
            { value: 'caregiver-training', label: 'Caregiver Training', order: 9 },
          ],
        },
        {
          id: 'patient-tolerance',
          text: 'Patient Tolerance of Treatment',
          type: 'single-select',
          required: true,
          order: 2,
          options: [
            { value: 'excellent', label: 'Excellent - No Adverse Reactions', order: 1 },
            { value: 'good', label: 'Good - Well Tolerated', order: 2 },
            { value: 'fair', label: 'Fair - Some Fatigue', order: 3 },
            { value: 'poor', label: 'Poor - Limited by Fatigue/Pain', order: 4 },
          ],
        },
        {
          id: 'patient-participation',
          text: 'Patient Participation/Engagement',
          type: 'single-select',
          required: true,
          order: 3,
          options: [
            { value: 'excellent', label: 'Excellent - Highly Engaged', order: 1 },
            { value: 'good', label: 'Good - Cooperative', order: 2 },
            { value: 'fair', label: 'Fair - Somewhat Cooperative', order: 3 },
            { value: 'poor', label: 'Poor - Uncooperative/Resistant', order: 4 },
          ],
        },
      ],
    },

    {
      id: 'goals-plan',
      title: 'Goals & Plan of Care',
      description: 'Treatment goals and ongoing plan',
      order: 7,
      questions: [
        {
          id: 'short-term-goals',
          text: 'Short-Term Goals (2-4 weeks)',
          type: 'long-text',
          required: true,
          order: 1,
          helpText: 'Specific, measurable, functional goals',
        },
        {
          id: 'long-term-goals',
          text: 'Long-Term Goals (Episode of Care)',
          type: 'long-text',
          required: true,
          order: 2,
          helpText: 'Functional independence goals',
        },
        {
          id: 'treatment-frequency',
          text: 'Recommended Treatment Frequency',
          type: 'single-select',
          required: true,
          order: 3,
          options: [
            { value: '1x-week', label: '1x per week', order: 1 },
            { value: '2x-week', label: '2x per week', order: 2 },
            { value: '3x-week', label: '3x per week', order: 3 },
            { value: '4x-week', label: '4x per week', order: 4 },
            { value: '5x-week', label: '5x per week', order: 5 },
          ],
        },
        {
          id: 'estimated-duration',
          text: 'Estimated Duration of Care',
          type: 'single-select',
          required: true,
          order: 4,
          options: [
            { value: '2-weeks', label: '2 weeks', order: 1 },
            { value: '4-weeks', label: '4 weeks', order: 2 },
            { value: '6-weeks', label: '6 weeks', order: 3 },
            { value: '8-weeks', label: '8 weeks', order: 4 },
            { value: '12-weeks', label: '12 weeks', order: 5 },
          ],
        },
        {
          id: 'rehab-potential',
          text: 'Rehabilitation Potential',
          type: 'single-select',
          required: true,
          order: 5,
          options: [
            { value: 'excellent', label: 'Excellent', order: 1 },
            { value: 'good', label: 'Good', order: 2 },
            { value: 'fair', label: 'Fair', order: 3 },
            { value: 'poor', label: 'Poor', order: 4 },
          ],
        },
        {
          id: 'hep-provided',
          text: 'Home Program Provided',
          type: 'boolean',
          required: true,
          order: 6,
        },
        {
          id: 'clinical-summary',
          text: 'Clinical Summary/Impression',
          type: 'long-text',
          required: true,
          order: 7,
          helpText: 'Overall clinical impression, functional status, and plan',
        },
      ],
    },
  ],

  regulatoryBody: 'AOTA/Medicare',
  effectiveDate: '2024-01-01',
  requiredTimeframe: {
    mustCompleteWithin: 24,
    timeUnit: 'hours',
  },

  completionRequirements: {
    minimumProgress: 100,
    requiredSections: [
      'visit-info',
      'adl-assessment',
      'iadl-assessment',
      'fine-motor-cognitive',
      'home-environment',
      'interventions',
      'goals-plan',
    ],
    requiredQuestions: [
      'visit-type',
      'visit-date',
      'referral-reason',
      'bathing',
      'dressing-upper',
      'dressing-lower',
      'interventions-provided',
      'short-term-goals',
      'long-term-goals',
      'clinical-summary',
    ],
  },
};

export default OCCUPATIONAL_THERAPY_CONFIGURATION;
