/**
 * WOUND CARE ASSESSMENT CONFIGURATION
 * 
 * Comprehensive wound assessment and treatment documentation
 * Includes detailed measurements, healing stages, treatment interventions
 * 
 * @version 1.0.0
 * @compliance NPUAP/EPUAP Guidelines, Medicare
 */

import type { AssessmentTypeConfiguration } from '../types/assessmentTypes';

export const WOUND_CARE_CONFIGURATION: AssessmentTypeConfiguration = {
  id: 'wound-care-assessment-2024',
  name: 'Wound Care Assessment',
  version: 'Wound Assessment v2024.1',
  category: 'specialized',
  
  sections: [
    {
      id: 'visit-wound-info',
      title: 'Visit & Wound Identification',
      order: 1,
      questions: [
        { id: 'visit-date', text: 'Visit Date', type: 'date', required: true, order: 1 },
        { id: 'wound-id', text: 'Wound Identifier', type: 'text', required: true, order: 2,
          helpText: 'e.g., "Right heel pressure injury" or "Surgical wound abdomen"',
        },
        { id: 'wound-type', text: 'Wound Type/Classification', type: 'single-select', required: true, order: 3,
          options: [
            { value: 'pressure-injury', label: 'Pressure Injury/Ulcer', order: 1 },
            { value: 'arterial-ulcer', label: 'Arterial Ulcer', order: 2 },
            { value: 'venous-ulcer', label: 'Venous Stasis Ulcer', order: 3 },
            { value: 'diabetic-ulcer', label: 'Diabetic Ulcer', order: 4 },
            { value: 'surgical', label: 'Surgical Wound', order: 5 },
            { value: 'traumatic', label: 'Traumatic Wound', order: 6 },
            { value: 'burn', label: 'Burn', order: 7 },
            { value: 'other', label: 'Other', order: 8 },
          ],
        },
        { id: 'wound-location', text: 'Anatomical Location', type: 'single-select', required: true, order: 4,
          options: [
            { value: 'head-face', label: 'Head/Face', order: 1 },
            { value: 'neck', label: 'Neck', order: 2 },
            { value: 'chest-anterior', label: 'Chest (Anterior)', order: 3 },
            { value: 'abdomen', label: 'Abdomen', order: 4 },
            { value: 'back-upper', label: 'Upper Back', order: 5 },
            { value: 'back-lower', label: 'Lower Back', order: 6 },
            { value: 'sacrum-coccyx', label: 'Sacrum/Coccyx', order: 7 },
            { value: 'buttocks-right', label: 'Right Buttock', order: 8 },
            { value: 'buttocks-left', label: 'Left Buttock', order: 9 },
            { value: 'hip-right', label: 'Right Hip/Trochanter', order: 10 },
            { value: 'hip-left', label: 'Left Hip/Trochanter', order: 11 },
            { value: 'thigh-right', label: 'Right Thigh', order: 12 },
            { value: 'thigh-left', label: 'Left Thigh', order: 13 },
            { value: 'knee-right', label: 'Right Knee', order: 14 },
            { value: 'knee-left', label: 'Left Knee', order: 15 },
            { value: 'leg-right', label: 'Right Lower Leg', order: 16 },
            { value: 'leg-left', label: 'Left Lower Leg', order: 17 },
            { value: 'ankle-right', label: 'Right Ankle', order: 18 },
            { value: 'ankle-left', label: 'Left Ankle', order: 19 },
            { value: 'heel-right', label: 'Right Heel', order: 20 },
            { value: 'heel-left', label: 'Left Heel', order: 21 },
            { value: 'foot-right', label: 'Right Foot', order: 22 },
            { value: 'foot-left', label: 'Left Foot', order: 23 },
            { value: 'arm-upper-right', label: 'Right Upper Arm', order: 24 },
            { value: 'arm-upper-left', label: 'Left Upper Arm', order: 25 },
            { value: 'elbow-right', label: 'Right Elbow', order: 26 },
            { value: 'elbow-left', label: 'Left Elbow', order: 27 },
            { value: 'forearm-right', label: 'Right Forearm', order: 28 },
            { value: 'forearm-left', label: 'Left Forearm', order: 29 },
            { value: 'hand-right', label: 'Right Hand', order: 30 },
            { value: 'hand-left', label: 'Left Hand', order: 31 },
          ],
        },
        { id: 'onset-date', text: 'Wound Onset Date', type: 'date', required: false, order: 5 },
        { id: 'etiology', text: 'Wound Etiology/Cause', type: 'text', required: false, order: 6 },
      ],
    },

    {
      id: 'wound-staging',
      title: 'Wound Staging & Classification',
      description: 'For pressure injuries and wound depth classification',
      order: 2,
      questions: [
        { id: 'pressure-injury-stage', text: 'Pressure Injury Stage', type: 'single-select', required: false, order: 1,
          options: [
            { value: 'stage-1', label: 'Stage 1 - Non-blanchable erythema', order: 1 },
            { value: 'stage-2', label: 'Stage 2 - Partial thickness loss', order: 2 },
            { value: 'stage-3', label: 'Stage 3 - Full thickness loss', order: 3 },
            { value: 'stage-4', label: 'Stage 4 - Full thickness with exposed tissue', order: 4 },
            { value: 'unstageable', label: 'Unstageable - Obscured by slough/eschar', order: 5 },
            { value: 'dti', label: 'Deep Tissue Injury (DTI)', order: 6 },
            { value: 'na', label: 'N/A - Not a pressure injury', order: 7 },
          ],
          conditional: { dependsOn: 'wound-type', showWhen: { equals: 'pressure-injury' } },
        },
        { id: 'wound-depth', text: 'Wound Depth Classification', type: 'single-select', required: false, order: 2,
          options: [
            { value: 'superficial', label: 'Superficial - Epidermis only', order: 1 },
            { value: 'partial-thickness', label: 'Partial Thickness - Into dermis', order: 2 },
            { value: 'full-thickness', label: 'Full Thickness - Through dermis', order: 3 },
            { value: 'deep', label: 'Deep - Involves muscle/bone/tendon', order: 4 },
          ],
        },
      ],
    },

    {
      id: 'measurements',
      title: 'Wound Measurements',
      description: 'Accurate wound dimensions',
      order: 3,
      questions: [
        { id: 'length', text: 'Length (longest dimension in cm)', type: 'number', required: true, order: 1,
          validation: { min: 0, max: 100 },
          helpText: 'Head to toe direction',
        },
        { id: 'width', text: 'Width (widest dimension in cm)', type: 'number', required: true, order: 2,
          validation: { min: 0, max: 100 },
          helpText: 'Side to side direction',
        },
        { id: 'depth', text: 'Depth (in cm)', type: 'number', required: false, order: 3,
          validation: { min: 0, max: 50 },
          helpText: 'Deepest point measured',
        },
        { id: 'undermining', text: 'Undermining Present', type: 'boolean', required: true, order: 4 },
        { id: 'undermining-location', text: 'Undermining Location (Clock Position)', type: 'text', required: false, order: 5,
          helpText: 'e.g., "12 o\'clock to 3 o\'clock"',
          conditional: { dependsOn: 'undermining', showWhen: { equals: true } },
        },
        { id: 'undermining-depth', text: 'Undermining Depth (cm)', type: 'number', required: false, order: 6,
          validation: { min: 0, max: 50 },
          conditional: { dependsOn: 'undermining', showWhen: { equals: true } },
        },
        { id: 'tunneling', text: 'Tunneling/Sinus Tract Present', type: 'boolean', required: true, order: 7 },
        { id: 'tunneling-location', text: 'Tunneling Location (Clock Position)', type: 'text', required: false, order: 8,
          conditional: { dependsOn: 'tunneling', showWhen: { equals: true } },
        },
        { id: 'tunneling-depth', text: 'Tunneling Depth (cm)', type: 'number', required: false, order: 9,
          validation: { min: 0, max: 50 },
          conditional: { dependsOn: 'tunneling', showWhen: { equals: true } },
        },
      ],
    },

    {
      id: 'wound-bed',
      title: 'Wound Bed Assessment',
      description: 'Tissue types and percentages',
      order: 4,
      questions: [
        { id: 'tissue-types', text: 'Tissue Types Present', type: 'multi-select', required: true, order: 1,
          options: [
            { value: 'granulation', label: 'Granulation (red, beefy)', order: 1 },
            { value: 'epithelial', label: 'Epithelial (pink)', order: 2 },
            { value: 'slough', label: 'Slough (yellow, tan)', order: 3 },
            { value: 'eschar', label: 'Eschar (black, brown)', order: 4 },
            { value: 'necrotic', label: 'Necrotic Tissue', order: 5 },
            { value: 'tendon', label: 'Exposed Tendon', order: 6 },
            { value: 'bone', label: 'Exposed Bone', order: 7 },
            { value: 'muscle', label: 'Exposed Muscle', order: 8 },
          ],
        },
        { id: 'granulation-percent', text: 'Granulation Tissue (%)', type: 'number', required: false, order: 2,
          validation: { min: 0, max: 100 },
        },
        { id: 'slough-percent', text: 'Slough (%)', type: 'number', required: false, order: 3,
          validation: { min: 0, max: 100 },
        },
        { id: 'eschar-percent', text: 'Eschar (%)', type: 'number', required: false, order: 4,
          validation: { min: 0, max: 100 },
        },
        { id: 'necrotic-percent', text: 'Necrotic Tissue (%)', type: 'number', required: false, order: 5,
          validation: { min: 0, max: 100 },
        },
      ],
    },

    {
      id: 'exudate',
      title: 'Wound Exudate/Drainage',
      order: 5,
      questions: [
        { id: 'exudate-amount', text: 'Exudate Amount', type: 'single-select', required: true, order: 1,
          options: [
            { value: 'none', label: 'None', order: 1 },
            { value: 'scant', label: 'Scant', order: 2 },
            { value: 'small', label: 'Small', order: 3 },
            { value: 'moderate', label: 'Moderate', order: 4 },
            { value: 'large', label: 'Large', order: 5 },
            { value: 'copious', label: 'Copious', order: 6 },
          ],
        },
        { id: 'exudate-type', text: 'Exudate Type/Color', type: 'multi-select', required: false, order: 2,
          options: [
            { value: 'serous', label: 'Serous (clear, watery)', order: 1 },
            { value: 'serosanguineous', label: 'Serosanguineous (pink, blood-tinged)', order: 2 },
            { value: 'sanguineous', label: 'Sanguineous (bloody)', order: 3 },
            { value: 'purulent', label: 'Purulent (thick, opaque)', order: 4 },
          ],
        },
        { id: 'exudate-odor', text: 'Odor Present', type: 'boolean', required: true, order: 3 },
        { id: 'odor-description', text: 'Odor Description', type: 'single-select', required: false, order: 4,
          options: [
            { value: 'faint', label: 'Faint', order: 1 },
            { value: 'moderate', label: 'Moderate', order: 2 },
            { value: 'strong', label: 'Strong', order: 3 },
            { value: 'foul', label: 'Foul/Offensive', order: 4 },
          ],
          conditional: { dependsOn: 'exudate-odor', showWhen: { equals: true } },
        },
      ],
    },

    {
      id: 'periwound',
      title: 'Periwound Skin Assessment',
      description: 'Surrounding skin condition',
      order: 6,
      questions: [
        { id: 'periwound-condition', text: 'Periwound Skin Condition', type: 'multi-select', required: true, order: 1,
          options: [
            { value: 'intact', label: 'Intact', order: 1 },
            { value: 'erythema', label: 'Erythema/Redness', order: 2 },
            { value: 'maceration', label: 'Maceration', order: 3 },
            { value: 'induration', label: 'Induration/Hardness', order: 4 },
            { value: 'edema', label: 'Edema/Swelling', order: 5 },
            { value: 'dry-scaling', label: 'Dry/Scaling', order: 6 },
            { value: 'callus', label: 'Callus Formation', order: 7 },
            { value: 'discoloration', label: 'Discoloration', order: 8 },
          ],
        },
        { id: 'wound-edges', text: 'Wound Edge Characteristics', type: 'multi-select', required: false, order: 2,
          options: [
            { value: 'attached', label: 'Attached/Well-defined', order: 1 },
            { value: 'rolled', label: 'Rolled/Epibole', order: 2 },
            { value: 'irregular', label: 'Irregular', order: 3 },
            { value: 'macerated', label: 'Macerated', order: 4 },
          ],
        },
      ],
    },

    {
      id: 'infection-signs',
      title: 'Signs of Infection',
      order: 7,
      questions: [
        { id: 'infection-signs', text: 'Signs of Infection Present', type: 'multi-select', required: true, order: 1,
          options: [
            { value: 'none', label: 'No Signs of Infection', order: 1 },
            { value: 'increased-pain', label: 'Increased Pain/Tenderness', order: 2 },
            { value: 'erythema', label: 'Erythema/Warmth', order: 3 },
            { value: 'purulent-drainage', label: 'Purulent Drainage', order: 4 },
            { value: 'foul-odor', label: 'Foul Odor', order: 5 },
            { value: 'increased-drainage', label: 'Increased Drainage', order: 6 },
            { value: 'delayed-healing', label: 'Delayed Healing', order: 7 },
          ],
        },
        { id: 'fever', text: 'Patient Has Fever', type: 'boolean', required: false, order: 2 },
        { id: 'physician-notified', text: 'Physician Notified of Infection Signs', type: 'boolean', required: false, order: 3,
          conditional: { dependsOn: 'infection-signs', showWhen: { includesAny: ['increased-pain', 'purulent-drainage', 'foul-odor'] } },
        },
      ],
    },

    {
      id: 'treatment-interventions',
      title: 'Treatment & Interventions',
      description: 'Wound care procedures performed',
      order: 8,
      questions: [
        { id: 'wound-cleansed', text: 'Wound Cleansed', type: 'boolean', required: true, order: 1 },
        { id: 'cleansing-solution', text: 'Cleansing Solution Used', type: 'single-select', required: false, order: 2,
          options: [
            { value: 'normal-saline', label: 'Normal Saline', order: 1 },
            { value: 'wound-cleanser', label: 'Commercial Wound Cleanser', order: 2 },
            { value: 'sterile-water', label: 'Sterile Water', order: 3 },
            { value: 'other', label: 'Other', order: 4 },
          ],
          conditional: { dependsOn: 'wound-cleansed', showWhen: { equals: true } },
        },
        { id: 'debridement', text: 'Debridement Performed', type: 'boolean', required: true, order: 3 },
        { id: 'debridement-type', text: 'Type of Debridement', type: 'single-select', required: false, order: 4,
          options: [
            { value: 'sharp', label: 'Sharp/Surgical', order: 1 },
            { value: 'enzymatic', label: 'Enzymatic', order: 2 },
            { value: 'autolytic', label: 'Autolytic', order: 3 },
            { value: 'mechanical', label: 'Mechanical', order: 4 },
          ],
          conditional: { dependsOn: 'debridement', showWhen: { equals: true } },
        },
        { id: 'primary-dressing', text: 'Primary Dressing Applied', type: 'single-select', required: true, order: 5,
          options: [
            { value: 'gauze-dry', label: 'Dry Gauze', order: 1 },
            { value: 'gauze-saline', label: 'Saline-moistened Gauze', order: 2 },
            { value: 'foam', label: 'Foam Dressing', order: 3 },
            { value: 'hydrocolloid', label: 'Hydrocolloid', order: 4 },
            { value: 'hydrogel', label: 'Hydrogel', order: 5 },
            { value: 'alginate', label: 'Alginate', order: 6 },
            { value: 'collagen', label: 'Collagen', order: 7 },
            { value: 'antimicrobial', label: 'Antimicrobial (Silver, etc.)', order: 8 },
            { value: 'transparent-film', label: 'Transparent Film', order: 9 },
            { value: 'vac', label: 'Negative Pressure/VAC', order: 10 },
          ],
        },
        { id: 'secondary-dressing', text: 'Secondary Dressing Applied', type: 'single-select', required: false, order: 6,
          options: [
            { value: 'none', label: 'None', order: 1 },
            { value: 'gauze', label: 'Gauze Wrap', order: 2 },
            { value: 'abdominal-pad', label: 'ABD Pad', order: 3 },
            { value: 'tape', label: 'Tape Only', order: 4 },
            { value: 'elastic-wrap', label: 'Elastic Wrap', order: 5 },
          ],
        },
        { id: 'topical-agent', text: 'Topical Agent Applied', type: 'text', required: false, order: 7,
          helpText: 'e.g., antibiotic ointment, barrier cream, enzymatic debriding agent',
        },
        { id: 'compression-therapy', text: 'Compression Therapy Applied', type: 'boolean', required: false, order: 8 },
        { id: 'offloading-device', text: 'Offloading Device Used', type: 'boolean', required: false, order: 9 },
      ],
    },

    {
      id: 'healing-progress',
      title: 'Healing Progress & Plan',
      order: 9,
      questions: [
        { id: 'healing-status', text: 'Healing Status/Trend', type: 'single-select', required: true, order: 1,
          options: [
            { value: 'healed', label: 'Healed/Closed', order: 1 },
            { value: 'improved', label: 'Improved - Decreasing in size', order: 2 },
            { value: 'stable', label: 'Stable - No change', order: 3 },
            { value: 'deteriorating', label: 'Deteriorating - Increasing in size', order: 4 },
            { value: 'new-wound', label: 'New Wound - Baseline', order: 5 },
          ],
        },
        { id: 'comparison-prior', text: 'Comparison to Prior Visit', type: 'long-text', required: false, order: 2,
          helpText: 'Note changes in size, depth, drainage, or appearance',
        },
        { id: 'barriers-to-healing', text: 'Barriers to Healing', type: 'multi-select', required: false, order: 3,
          options: [
            { value: 'poor-nutrition', label: 'Poor Nutrition', order: 1 },
            { value: 'diabetes', label: 'Uncontrolled Diabetes', order: 2 },
            { value: 'circulation', label: 'Poor Circulation', order: 3 },
            { value: 'infection', label: 'Infection', order: 4 },
            { value: 'pressure', label: 'Continued Pressure/Friction', order: 5 },
            { value: 'non-compliance', label: 'Non-compliance with Treatment', order: 6 },
            { value: 'medication', label: 'Medications (steroids, etc.)', order: 7 },
          ],
        },
        { id: 'expected-outcome', text: 'Expected Healing Timeframe', type: 'single-select', required: false, order: 4,
          options: [
            { value: '1-2-weeks', label: '1-2 weeks', order: 1 },
            { value: '3-4-weeks', label: '3-4 weeks', order: 2 },
            { value: '5-8-weeks', label: '5-8 weeks', order: 3 },
            { value: '9-12-weeks', label: '9-12 weeks', order: 4 },
            { value: 'extended', label: 'Extended (>12 weeks)', order: 5 },
            { value: 'chronic', label: 'Chronic - May not fully heal', order: 6 },
          ],
        },
        { id: 'next-visit-plan', text: 'Plan for Next Visit', type: 'long-text', required: true, order: 5,
          helpText: 'Dressing change frequency, continued treatments, goals',
        },
        { id: 'patient-education', text: 'Patient/Caregiver Education Provided', type: 'multi-select', required: false, order: 6,
          options: [
            { value: 'wound-care', label: 'Wound Care Technique', order: 1 },
            { value: 'signs-infection', label: 'Signs of Infection', order: 2 },
            { value: 'nutrition', label: 'Nutrition for Healing', order: 3 },
            { value: 'pressure-relief', label: 'Pressure Relief/Repositioning', order: 4 },
            { value: 'when-to-call', label: 'When to Call Nurse/Physician', order: 5 },
          ],
        },
      ],
    },
  ],

  regulatoryBody: 'NPUAP/EPUAP/Medicare',
  effectiveDate: '2024-01-01',
  requiredTimeframe: { mustCompleteWithin: 24, timeUnit: 'hours' },
  completionRequirements: {
    minimumProgress: 100,
    requiredSections: ['visit-wound-info', 'wound-staging', 'measurements', 'wound-bed', 'exudate', 'periwound', 'infection-signs', 'treatment-interventions', 'healing-progress'],
    requiredQuestions: ['visit-date', 'wound-id', 'wound-type', 'wound-location', 'length', 'width', 'tissue-types', 'exudate-amount', 'primary-dressing', 'healing-status', 'next-visit-plan'],
  },
};

export default WOUND_CARE_CONFIGURATION;
