/**
 * Caregiver Mock Data Generator
 * 
 * Generates realistic mock data for caregiver profiles.
 */

import type { CaregiverProfile, DisciplineType } from './caregiverTypes';

export function generateMockCaregiverProfile(): CaregiverProfile {
  const now = new Date();

  return {
    id: 'caregiver-001',
    personalInfo: {
      firstName: 'Sarah',
      lastName: 'Johnson',
      preferredName: 'Sarah',
      email: 'sarah.johnson@homehealth.com',
      phone: '(555) 123-4567',
      alternatePhone: '(555) 987-6543',
      address: {
        street: '1234 Healthcare Drive',
        city: 'Boston',
        state: 'MA',
        zipCode: '02101',
      },
      dateOfBirth: '1985-03-15',
      emergencyContact: {
        name: 'Michael Johnson',
        relationship: 'Spouse',
        phone: '(555) 111-2222',
      },
    },
    disciplines: [
      {
        type: 'SN',
        isPrimary: true,
        yearsExperience: 12,
        specialties: ['Wound Care', 'Diabetes Management', 'Post-Op Care'],
      },
      {
        type: 'HHA',
        isPrimary: false,
        yearsExperience: 8,
        specialties: [],
      },
    ],
    primaryDiscipline: 'SN',
    licenses: [
      {
        id: 'lic-1',
        type: 'RN License',
        licenseNumber: 'RN123456',
        state: 'MA',
        issueDate: '2012-06-15',
        expirationDate: '2025-06-15',
        status: 'active',
        verificationDate: '2024-01-15',
      },
      {
        id: 'lic-2',
        type: 'RN License',
        licenseNumber: 'RN654321',
        state: 'NH',
        issueDate: '2015-03-01',
        expirationDate: '2026-03-01',
        status: 'active',
        verificationDate: '2024-02-01',
      },
    ],
    certifications: [
      {
        id: 'cert-1',
        name: 'BLS (Basic Life Support)',
        issuer: 'American Heart Association',
        certificationNumber: 'BLS-12345',
        issueDate: '2023-06-01',
        expirationDate: '2025-06-01',
        status: 'current',
        requiresRenewal: true,
      },
      {
        id: 'cert-2',
        name: 'ACLS (Advanced Cardiac Life Support)',
        issuer: 'American Heart Association',
        certificationNumber: 'ACLS-67890',
        issueDate: '2023-07-15',
        expirationDate: '2025-07-15',
        status: 'current',
        requiresRenewal: true,
      },
      {
        id: 'cert-3',
        name: 'OASIS-E Certification',
        issuer: 'CMS',
        issueDate: '2022-01-10',
        expirationDate: new Date(now.getFullYear(), now.getMonth() + 1, 15).toISOString(),
        status: 'expiring-soon',
        requiresRenewal: true,
      },
      {
        id: 'cert-4',
        name: 'Wound Care Specialist',
        issuer: 'WOCN',
        certificationNumber: 'WCS-54321',
        issueDate: '2021-09-01',
        expirationDate: '2026-09-01',
        status: 'current',
        requiresRenewal: true,
      },
    ],
    training: [
      {
        id: 'train-1',
        name: 'HIPAA Compliance Training',
        category: 'Compliance',
        completionDate: '2024-01-15',
        expirationDate: '2025-01-15',
        hours: 2,
        instructor: 'Compliance Department',
        status: 'completed',
      },
      {
        id: 'train-2',
        name: 'Infection Control',
        category: 'Safety',
        completionDate: '2024-02-01',
        expirationDate: '2025-02-01',
        hours: 4,
        instructor: 'Safety Officer',
        status: 'completed',
      },
      {
        id: 'train-3',
        name: 'Advanced Wound Care Techniques',
        category: 'Clinical',
        completionDate: '2023-11-10',
        hours: 8,
        instructor: 'Dr. Patricia Williams',
        status: 'completed',
      },
      {
        id: 'train-4',
        name: 'Documentation Best Practices',
        category: 'Clinical',
        completionDate: '2024-03-01',
        hours: 3,
        instructor: 'Clinical Director',
        status: 'completed',
      },
      {
        id: 'train-5',
        name: 'Emergency Response Protocol',
        category: 'Safety',
        completionDate: '2024-01-20',
        expirationDate: '2025-01-20',
        hours: 2,
        status: 'completed',
      },
    ],
    availability: {
      status: 'available',
      weeklyPreferences: [
        { dayOfWeek: 1, startTime: '08:00', endTime: '17:00' }, // Monday
        { dayOfWeek: 2, startTime: '08:00', endTime: '17:00' }, // Tuesday
        { dayOfWeek: 3, startTime: '08:00', endTime: '17:00' }, // Wednesday
        { dayOfWeek: 4, startTime: '08:00', endTime: '17:00', maxHours: 8 }, // Thursday
        { dayOfWeek: 5, startTime: '08:00', endTime: '14:00', maxHours: 6 }, // Friday
      ],
      maxWeeklyHours: 40,
      maxDailyHours: 9,
      preferredTerritory: ['Downtown Boston', 'Cambridge', 'Somerville'],
      travelRadius: 25,
      restrictions: ['No overnight shifts', 'No weekends'],
      notes: 'Prefers morning starts. Available for on-call rotation.',
    },
    employment: {
      employeeId: 'EMP-2012-045',
      hireDate: '2012-06-01',
      status: 'active',
      office: 'Boston Main Office',
      officeId: 'office-001',
      department: 'Clinical Services',
      supervisor: 'Jennifer Martinez, RN',
      supervisorId: 'sup-012',
      payRate: 45.50,
      payType: 'hourly',
      employmentType: 'full-time',
      benefitsEligible: true,
    },
    documents: [
      {
        id: 'doc-1',
        name: 'RN License - Massachusetts',
        type: 'License',
        category: 'Credentials',
        uploadDate: '2024-01-15',
        expirationDate: '2025-06-15',
        fileUrl: '/documents/rn-license-ma.pdf',
        fileSize: 245760,
        uploadedBy: 'HR Department',
      },
      {
        id: 'doc-2',
        name: 'BLS Certification Card',
        type: 'Certification',
        category: 'Credentials',
        uploadDate: '2023-06-01',
        expirationDate: '2025-06-01',
        fileUrl: '/documents/bls-cert.pdf',
        fileSize: 153600,
        uploadedBy: 'Sarah Johnson',
      },
      {
        id: 'doc-3',
        name: 'I-9 Employment Eligibility',
        type: 'I-9',
        category: 'HR Documents',
        uploadDate: '2012-06-01',
        fileUrl: '/documents/i9.pdf',
        fileSize: 327680,
        uploadedBy: 'HR Department',
      },
      {
        id: 'doc-4',
        name: 'TB Test Results',
        type: 'Health Screening',
        category: 'HR Documents',
        uploadDate: '2024-01-10',
        expirationDate: '2025-01-10',
        fileUrl: '/documents/tb-test.pdf',
        fileSize: 102400,
        uploadedBy: 'Occupational Health',
      },
      {
        id: 'doc-5',
        name: 'Annual Performance Review 2023',
        type: 'Performance Review',
        category: 'HR Documents',
        uploadDate: '2024-01-05',
        fileUrl: '/documents/performance-2023.pdf',
        fileSize: 409600,
        uploadedBy: 'Jennifer Martinez',
      },
      {
        id: 'doc-6',
        name: 'OASIS-E Certification',
        type: 'Certification',
        category: 'Credentials',
        uploadDate: '2022-01-10',
        expirationDate: new Date(now.getFullYear(), now.getMonth() + 1, 15).toISOString(),
        fileUrl: '/documents/oasis-cert.pdf',
        fileSize: 204800,
        uploadedBy: 'Training Department',
      },
    ],
    credentialCompliance: {
      overall: 'warning',
      lastReviewDate: '2024-03-01',
      nextReviewDate: '2024-09-01',
      issues: [
        {
          type: 'certification',
          severity: 'warning',
          message: 'OASIS-E Certification expires in 30 days - renewal required',
          itemId: 'cert-3',
          dueDate: new Date(now.getFullYear(), now.getMonth() + 1, 15).toISOString(),
        },
        {
          type: 'training',
          severity: 'info',
          message: 'Annual Safety Training due in 45 days',
          itemId: 'train-2',
          dueDate: '2025-02-01',
        },
      ],
    },
    createdAt: '2012-06-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  };
}
